export const supportedLanguages: string[] = [
    'javascript',
];

export const tooltipsIds: string[] = [
	'autoRepeat',
	'backward',
	'faster',
	'forward',
	'info',
	'nextInCategory',
	'playPause',
	'previousInCategory',
	'readCode',
	'rewind',
	'slower',
	'tabCodeToSign',
	'tabSignToCode',
	'tooltipToggle',
	'writeCode',
];

export const errors: any = {
    documentNotOpened: 'documentNotOpened',
    languageNotSupported: 'languageNotSupported',
    documentHasErrors: 'documentHasErrors',
    documentIsEmpty: 'documentIsEmpty',
};

export const signsMisc: any = {
	n0: {
		token: '0',
		directory: 'misc',
		file: undefined,
		examples: undefined,
	},
	n1: {
		token: '1',
		directory: 'misc',
		file: undefined,
		examples: undefined,
	},
	n2: {
		token: '2',
		directory: 'misc',
		file: undefined,
		examples: undefined,
	},
	n3: {
		token: '3',
		directory: 'misc',
		file: undefined,
		examples: undefined,
	},
	n4: {
		token: '4',
		directory: 'misc',
		file: undefined,
		examples: undefined,
	},
	n5: {
		token: '5',
		directory: 'misc',
		file: undefined,
		examples: undefined,
	},
	n6: {
		token: '6',
		directory: 'misc',
		file: undefined,
		examples: undefined,
	},
	n7: {
		token: '7',
		directory: 'misc',
		file: undefined,
		examples: undefined,
	},
	n8: {
		token: '8',
		directory: 'misc',
		file: undefined,
		examples: undefined,
	},
	n9: {
		token: '9',
		directory: 'misc',
		file: undefined,
		examples: undefined,
	},
	a: {
		token: 'a',
		directory: 'misc',
		file: undefined,
		examples: undefined,
	},
	b: {
		token: 'b',
		directory: 'misc',
		file: undefined,
		examples: undefined,
	},
	c: {
		token: 'c',
		directory: 'misc',
		file: undefined,
		examples: undefined,
	},
	ç: {
		token: 'ç',
		directory: 'misc',
		file: undefined,
		examples: undefined,
	},
	d: {
		token: 'd',
		directory: 'misc',
		file: undefined,
		examples: undefined,
	},
	e: {
		token: 'e',
		directory: 'misc',
		file: undefined,
		examples: undefined,
	},
	f: {
		token: 'f',
		directory: 'misc',
		file: undefined,
		examples: undefined,
	},
	g: {
		token: 'g',
		directory: 'misc',
		file: undefined,
		examples: undefined,
	},
	h: {
		token: 'h',
		directory: 'misc',
		file: undefined,
		examples: undefined,
	},
	i: {
		token: 'i',
		directory: 'misc',
		file: undefined,
		examples: undefined,
	},
	j: {
		token: 'j',
		directory: 'misc',
		file: undefined,
		examples: undefined,
	},
	k: {
		token: 'k',
		directory: 'misc',
		file: undefined,
		examples: undefined,
	},
	l: {
		token: 'l',
		directory: 'misc',
		file: undefined,
		examples: undefined,
	},
	m: {
		token: 'm',
		directory: 'misc',
		file: undefined,
		examples: undefined,
	},
	n: {
		token: 'n',
		directory: 'misc',
		file: undefined,
		examples: undefined,
	},
	o: {
		token: 'o',
		directory: 'misc',
		file: undefined,
		examples: undefined,
	},
	p: {
		token: 'p',
		directory: 'misc',
		file: undefined,
		examples: undefined,
	},
	q: {
		token: 'q',
		directory: 'misc',
		file: undefined,
		examples: undefined,
	},
	r: {
		token: 'r',
		directory: 'misc',
		file: undefined,
		examples: undefined,
	},
	s: {
		token: 's',
		directory: 'misc',
		file: undefined,
		examples: undefined,
	},
	t: {
		token: 't',
		directory: 'misc',
		file: undefined,
		examples: undefined,
	},
	u: {
		token: 'u',
		directory: 'misc',
		file: undefined,
		examples: undefined,
	},
	v: {
		token: 'v',
		directory: 'misc',
		file: undefined,
		examples: undefined,
	},
	w: {
		token: 'w',
		directory: 'misc',
		file: undefined,
		examples: undefined,
	},
	x: {
		token: 'x',
		directory: 'misc',
		file: undefined,
		examples: undefined,
	},
	y: {
		token: 'y',
		directory: 'misc',
		file: undefined,
		examples: undefined,
	},
	z: {
		token: 'z',
		directory: 'misc',
		file: undefined,
		examples: undefined,
	},
};