export const supportedLanguages: string[] = [
    'javascript',
];

export const tooltipsIds: string[] = [
	'autoRepeatToggle',
	'backward',
	'faster',
	'forward',
	'info',
	'nextInCategory',
	'playPause',
	'previousInCategory',
	'readCode',
	'rewind',
	'slower',
	'tabCodeToSign',
	'tabSignToCode',
	'tooltipToggle',
	'writeCode',
];

export const errors: any = {
    documentNotOpened: 'documentNotOpened',
    languageNotSupported: 'languageNotSupported',
    documentHasErrors: 'documentHasErrors',
    documentIsEmpty: 'documentIsEmpty',
};

export const signsMisc: any = {
	n0: {
		token: '0',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	n1: {
		token: '1',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	n2: {
		token: '2',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	n3: {
		token: '3',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	n4: {
		token: '4',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	n5: {
		token: '5',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	n6: {
		token: '6',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	n7: {
		token: '7',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	n8: {
		token: '8',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	n9: {
		token: '9',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	a: {
		token: 'a',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	b: {
		token: 'b',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	c: {
		token: 'c',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	ç: {
		token: 'ç',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	d: {
		token: 'd',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	e: {
		token: 'e',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	f: {
		token: 'f',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	g: {
		token: 'g',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	h: {
		token: 'h',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	i: {
		token: 'i',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	j: {
		token: 'j',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	k: {
		token: 'k',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	l: {
		token: 'l',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	m: {
		token: 'm',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	n: {
		token: 'n',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	o: {
		token: 'o',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	p: {
		token: 'p',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	q: {
		token: 'q',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	r: {
		token: 'r',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	s: {
		token: 's',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	t: {
		token: 't',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	u: {
		token: 'u',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	v: {
		token: 'v',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	w: {
		token: 'w',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	x: {
		token: 'x',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	y: {
		token: 'y',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	z: {
		token: 'z',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	punctuationDot: {
		token: '.',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	punctuationComma: {
		token: ',',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	punctuationQuestion: {
		token: '?',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	punctuationExclamation: {
		token: '!',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	punctuationColon: {
		token: ':',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	punctuationSemicolon: {
		token: ';',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	punctuationTilde: {
		token: '~',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	punctuationAccentAcute: {
		token: '´',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	punctuationAccentCircumflex: {
		token: '^',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	punctuationAccentGrave: {
		token: '`',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	punctuationQuotation: {
		token: '"',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	punctuationApostrophe: {
		token: '\'',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	punctuationSlash: {
		token: '/',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	punctuationSlashBack: {
		token: '\\',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	punctuationVerticalBar: {
		token: '|',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	punctuationBracketRoundBegin: {
		token: '(',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	punctuationBracketRoundEnd: {
		token: ')',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	punctuationBracketSquareBegin: {
		token: '[',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	punctuationBracketSquareEnd: {
		token: ']',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	punctuationBracketCurlyBegin: {
		token: '{',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	punctuationBracketCurlEnd: {
		token: '}',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	punctuationMinusOrHyphen: {
		token: '-',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	punctuationPlus: {
		token: '+',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	punctuationEqual: {
		token: '=',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	punctuationPercentage: {
		token: '%',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	punctuationDollar: {
		token: '$',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	punctuationAt: {
		token: '@',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	punctuationSharp: {
		token: '#',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	punctuationAmpersand: {
		token: '&',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	punctuationGreater: {
		token: '>',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	punctuationLesser: {
		token: '<',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
	punctuationUnderline: {
		token: '_',
		isCode: false,
		file: undefined,
		examples: undefined,
	},
};
