export const supportedLanguages: string[] = [
    'javascript',
];

export const tooltipsIds: string[] = [
	'goToCodeToSign',
	'goToSignToCode',
	'slower',
	'faster',
	'rewind',
	'backward',
	'playPause',
	'forward',
	'autoRepeatToggle',
	'tooltipToggle',
	'info',
	'codeToSignAgain',
	'previousInCategory',
	'nextInCategory',
	'writeExampleToCode',
];

export const errors: any = {
    documentNotOpened: 'documentNotOpened',
    languageNotSupported: 'languageNotSupported',
    documentHasErrors: 'documentHasErrors',
    documentIsEmpty: 'documentIsEmpty',
};

export const signsMisc: any = {
	number0: {
		token: '0',
		isCode: false,
		file: 'number0',
		example: undefined,
	},
	number1: {
		token: '1',
		isCode: false,
		file: 'number1',
		example: undefined,
	},
	number2: {
		token: '2',
		isCode: false,
		file: 'number2',
		example: undefined,
	},
	number3: {
		token: '3',
		isCode: false,
		file: 'number3',
		example: undefined,
	},
	number4: {
		token: '4',
		isCode: false,
		file: 'number4',
		example: undefined,
	},
	number5: {
		token: '5',
		isCode: false,
		file: 'number5',
		example: undefined,
	},
	number6: {
		token: '6',
		isCode: false,
		file: 'number6',
		example: undefined,
	},
	number7: {
		token: '7',
		isCode: false,
		file: 'number7',
		example: undefined,
	},
	number8: {
		token: '8',
		isCode: false,
		file: 'number8',
		example: undefined,
	},
	number9: {
		token: '9',
		isCode: false,
		file: 'number9',
		example: undefined,
	},
	letterA: {
		token: 'a',
		isCode: false,
		file: 'letterA',
		example: undefined,
	},
	letterB: {
		token: 'b',
		isCode: false,
		file: 'letterB',
		example: undefined,
	},
	letterC: {
		token: 'c',
		isCode: false,
		file: 'letterC',
		example: undefined,
	},
	letterÇ: {
		token: 'ç',
		isCode: false,
		file: 'letterÇ',
		example: undefined,
	},
	letterD: {
		token: 'd',
		isCode: false,
		file: 'letterD',
		example: undefined,
	},
	letterE: {
		token: 'e',
		isCode: false,
		file: 'letterE',
		example: undefined,
	},
	letterF: {
		token: 'f',
		isCode: false,
		file: 'letterF',
		example: undefined,
	},
	letterG: {
		token: 'g',
		isCode: false,
		file: 'letterG',
		example: undefined,
	},
	letterH: {
		token: 'h',
		isCode: false,
		file: 'letterH',
		example: undefined,
	},
	letterI: {
		token: 'i',
		isCode: false,
		file: 'letterI',
		example: undefined,
	},
	letterJ: {
		token: 'j',
		isCode: false,
		file: 'letterJ',
		example: undefined,
	},
	letterK: {
		token: 'k',
		isCode: false,
		file: 'letterK',
		example: undefined,
	},
	letterL: {
		token: 'l',
		isCode: false,
		file: 'letterL',
		example: undefined,
	},
	letterM: {
		token: 'm',
		isCode: false,
		file: 'letterM',
		example: undefined,
	},
	letterN: {
		token: 'n',
		isCode: false,
		file: 'letterN',
		example: undefined,
	},
	letterO: {
		token: 'o',
		isCode: false,
		file: 'letterO',
		example: undefined,
	},
	letterP: {
		token: 'p',
		isCode: false,
		file: 'letterP',
		example: undefined,
	},
	letterQ: {
		token: 'q',
		isCode: false,
		file: 'letterQ',
		example: undefined,
	},
	letterR: {
		token: 'r',
		isCode: false,
		file: 'letterR',
		example: undefined,
	},
	letterS: {
		token: 's',
		isCode: false,
		file: 'letterS',
		example: undefined,
	},
	letterT: {
		token: 't',
		isCode: false,
		file: 'letterT',
		example: undefined,
	},
	letterU: {
		token: 'u',
		isCode: false,
		file: 'letterU',
		example: undefined,
	},
	letterV: {
		token: 'v',
		isCode: false,
		file: 'letterV',
		example: undefined,
	},
	letterW: {
		token: 'w',
		isCode: false,
		file: 'letterW',
		example: undefined,
	},
	letterX: {
		token: 'x',
		isCode: false,
		file: 'letterX',
		example: undefined,
	},
	letterY: {
		token: 'y',
		isCode: false,
		file: 'letterY',
		example: undefined,
	},
	letterZ: {
		token: 'z',
		isCode: false,
		file: 'letterZ',
		example: undefined,
	},
	punctuationDot: {
		token: '.',
		isCode: false,
		file: 'punctuationDot',
		example: undefined,
	},
	punctuationComma: {
		token: ',',
		isCode: false,
		file: 'punctuationComma',
		example: undefined,
	},
	punctuationQuestion: {
		token: '?',
		isCode: false,
		file: 'punctuationQuestion',
		example: undefined,
	},
	punctuationExclamation: {
		token: '!',
		isCode: false,
		file: 'punctuationExclamation',
		example: undefined,
	},
	punctuationColon: {
		token: ':',
		isCode: false,
		file: 'punctuationColon',
		example: undefined,
	},
	punctuationSemicolon: {
		token: ';',
		isCode: false,
		file: 'punctuationSemicolon',
		example: undefined,
	},
	punctuationTilde: {
		token: '~',
		isCode: false,
		file: 'punctuationTilde',
		example: undefined,
	},
	punctuationAccentAcute: {
		token: '´',
		isCode: false,
		file: 'punctuationAccentAcute',
		example: undefined,
	},
	punctuationAccentCircumflex: {
		token: '^',
		isCode: false,
		file: 'punctuationAccentCircumflex',
		example: undefined,
	},
	punctuationAccentGrave: {
		token: '`',
		isCode: false,
		file: 'punctuationAccentGrave',
		example: undefined,
	},
	punctuationQuotation: {
		token: '"',
		isCode: false,
		file: 'punctuationQuotation',
		example: undefined,
	},
	punctuationApostrophe: {
		token: '\'',
		isCode: false,
		file: 'punctuationApostrophe',
		example: undefined,
	},
	punctuationSlash: {
		token: '/',
		isCode: false,
		file: 'punctuationSlash',
		example: undefined,
	},
	punctuationSlashBack: {
		token: '\\',
		isCode: false,
		file: 'punctuationSlashBack',
		example: undefined,
	},
	punctuationPipe: {
		token: '|',
		isCode: false,
		file: 'punctuationPipe',
		example: undefined,
	},
	punctuationBracketRoundBegin: {
		token: '(',
		isCode: false,
		file: 'punctuationBracketRoundBegin',
		example: undefined,
	},
	punctuationBracketRoundEnd: {
		token: ')',
		isCode: false,
		file: 'punctuationBracketRoundEnd',
		example: undefined,
	},
	punctuationBracketSquareBegin: {
		token: '[',
		isCode: false,
		file: 'punctuationBracketSquareBegin',
		example: undefined,
	},
	punctuationBracketSquareEnd: {
		token: ']',
		isCode: false,
		file: 'punctuationBracketSquareEnd',
		example: undefined,
	},
	punctuationBracketCurlyBegin: {
		token: '{',
		isCode: false,
		file: 'punctuationBracketCurlyBegin',
		example: undefined,
	},
	punctuationBracketCurlyEnd: {
		token: '}',
		isCode: false,
		file: 'punctuationBracketCurlyEnd',
		example: undefined,
	},
	punctuationMinusOrHyphen: {
		token: '-',
		isCode: false,
		file: 'punctuationMinusOrHyphen',
		example: undefined,
	},
	punctuationPlus: {
		token: '+',
		isCode: false,
		file: 'punctuationPlus',
		example: undefined,
	},
	punctuationAsterisk: {
		token: '*',
		isCode: false,
		file: 'punctuationAsterisk',
		example: undefined,
	},
	punctuationPercentage: {
		token: '%',
		isCode: false,
		file: 'punctuationPercentage',
		example: undefined,
	},
	punctuationDollar: {
		token: '$',
		isCode: false,
		file: 'punctuationDollar',
		example: undefined,
	},
	punctuationAt: {
		token: '@',
		isCode: false,
		file: 'punctuationAt',
		example: undefined,
	},
	punctuationSharp: {
		token: '#',
		isCode: false,
		file: 'punctuationSharp',
		example: undefined,
	},
	punctuationAmpersand: {
		token: '&',
		isCode: false,
		file: 'punctuationAmpersand',
		example: undefined,
	},
	punctuationGreater: {
		token: '>',
		isCode: false,
		file: 'punctuationGreater',
		example: undefined,
	},
	punctuationLesser: {
		token: '<',
		isCode: false,
		file: 'punctuationLesser',
		example: undefined,
	},
	punctuationUnderline: {
		token: '_',
		isCode: false,
		file: 'punctuationUnderline',
		example: undefined,
	},
};
